workflows:
  build_ios_simulator:
    name: Build iOS Simulator App
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install dependencies
        script: flutter pub get

      - name: Build iOS Simulator App
        script: flutter build ios --simulator --debug

      - name: Zip Simulator App
        script: |
          cd build/ios/iphonesimulator
          zip -r Simulator-Runner.app.zip Runner.app

    artifacts:
      - build/ios/iphonesimulator/Simulator-Runner.app.zip