default_platform(:ios)

platform :ios do
  desc "Build and sign the iOS app"
  lane :build_release do
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store"
    )
  end

  desc "Upload build to TestFlight"
  lane :upload_testflight do
    pilot upload: true
  end
end

